baseURL = 'https://fabiorehm.com/'
defaultContentLanguage = 'en'
title = 'fabiorehm.com'
theme = 'hugo-coder'
copyright = "&copy; <a href=\"https://github.com/fgrehm\">Fabio Rehm</a> 2013-2025"
enableEmoji = true
enableRobotsTXT = true
languageCode = "en"

# Modern Hugo pagination configuration
[pagination]
  pagerSize = 5

# https://gohugo.io/content-management/multilingual/
[languages]
  [languages.en]
    contentDir = 'content/en'
    languageName = 'English'
    weight = 1

# Modern Hugo services configuration
[services]
  [services.disqus]
    shortname = "fgrehm"
  [services.googleAnalytics]
    ID = "G-3SYR4MH1JV"

# Allow raw HTML in markdown (needed for older blog posts)
[markup]
  [markup.highlight]
    noClasses = false
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

# Hugo Coder theme parameters
[params]
  author = "Fabio Rehm"
  description = "Rails developer, DevOps tinkerer, and open source contributor. Writing about practical solutions and tools that make development life easier."
  keywords = "blog,developer,rails,devops,vagrant,docker,ruby"
  info = ["Software Engineer"]
  dateFormat = "January 2, 2006"
  since = 2013
  # Use Gravatar for avatar based on email
  gravatar = "fgrehm@gmail.com"
  colorScheme = "auto"
  hideColorSchemeToggle = false
  maxSeeAlsoItems = 5
  customCSS = ["css/site.css"]

# Social media links
[[params.social]]
  name = "GitHub"
  icon = "fa-brands fa-github fa-2x"
  weight = 1
  url = "https://github.com/fgrehm"

[[params.social]]
  name = "LinkedIn"
  icon = "fa-brands fa-linkedin fa-2x"
  weight = 2
  url = "https://linkedin.com/in/fgrehm"

[[params.social]]
  name = "Email"
  icon = "fa-solid fa-envelope fa-2x"
  weight = 3
  url = "mailto:site@fabiorehm.com"

[[params.social]]
  name = "RSS"
  icon = "fa-solid fa-rss fa-2x"
  weight = 4
  url = "https://fabiorehm.com/index.xml"
  rel = "alternate"
  type = "application/rss+xml"

# English menu
[[languages.en.menu.main]]
  name = "Blog"
  weight = 1
  url = "blog/"

[[languages.en.menu.main]]
  name = "About"
  weight = 2
  url = "about/"

# Taxonomies
[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

# GitHub Discussions integration
[params.githubDiscussions]
  enabled = true
  repo = "fgrehm/fabiorehm.com"
  category = "blog-posts"
